name: CI
on:
  push:
    branches: master
  # pull_request:
  #   branches: master

jobs:
  build:
    name: Nix build
    runs-on: ubuntu-latest # self-hosted
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: ryanccn/attic-action@v0
      with:
        endpoint: https://nix-cache.cajun.page
        cache: public
        token: ${{ secrets.ATTIC_TOKEN }}
    - name: Nix build
      run: nix build --accept-flake-config --print-build-logs
    - name: Nix flake check
      run: nix flake check --accept-flake-config
